name: manual-workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        default: 'dev'
        required: false
      version:
        description: 'Released version'
        required: true

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
